import AppKit
import CryptoKit
import Foundation
import UniformTypeIdentifiers

nonisolated struct ClipboardItem: Sendable {
    let generation: Int
    let data: Data?
    let fileURL: URL?
    let typeIdentifier: String

    static func preferredType(_ types: [NSPasteboard.PasteboardType]) -> NSPasteboard.PasteboardType? {
        let excluded = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                        "org.nspasteboard.AutoGeneratedType", "com.orbitconvert.optimized"]
        guard !types.contains(where: { excluded.contains($0.rawValue) }) else { return nil }
        return [NSPasteboard.PasteboardType.fileURL, .png, .init(UTType.jpeg.identifier),
                .init(UTType.heic.identifier), .tiff].first { types.contains($0) }
    }
}

nonisolated struct ClipboardOptimizationResult: Identifiable, Sendable {
    let id = UUID()
    let data: Data
    let typeIdentifier: String
    let originalBytes: Int64
    let width: Int
    let height: Int
    let thumbnailData: Data
    let duration: TimeInterval
    let sourceFingerprint: String
    let outputFingerprint: String
    let fileBacked: Bool
    var savedBytes: Int64 { max(originalBytes - Int64(data.count), 0) }
    var percentage: Double? { originalBytes > 0 ? Double(savedBytes) / Double(originalBytes) * 100 : nil }
    var fileExtension: String { UTType(typeIdentifier)?.preferredFilenameExtension ?? "png" }
}

nonisolated struct ClipboardFingerprintRegistry {
    private var entries: [(String, Date)] = []
    var count: Int { entries.count }
    static func fingerprint(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
    func contains(_ fingerprint: String, now: Date = Date()) -> Bool {
        entries.contains { $0.0 == fingerprint && now.timeIntervalSince($0.1) < 3600 }
    }
    mutating func insert(_ fingerprint: String, now: Date = Date()) {
        entries = Array((entries.filter { $0.0 != fingerprint && now.timeIntervalSince($0.1) < 3600 }
            + [(fingerprint, now)]).suffix(128))
    }
}
